import mitt from 'mitt';

import {
  EVENTBUS_INBOX_MESSAGE,
  EVENTBUS_SOCKET_DISCONNECT,
  EVENTBUS_SOCKET_CONNECT,
  EVENTBUS_SOCKET_RECONNECT_ATTEMPT,
  EVENTBUS_SOCKET_RECONNECT_ERROR,
  EVENTBUS_SOCKET_RECONNECT_FAILED,
} from '@/core/settings/constants';

export type AppEvents = {
  [EVENTBUS_INBOX_MESSAGE]: any;
  [EVENTBUS_SOCKET_DISCONNECT]: void;
  [EVENTBUS_SOCKET_CONNECT]: void;
  [EVENTBUS_SOCKET_RECONNECT_ATTEMPT]: void;
  [EVENTBUS_SOCKET_RECONNECT_ERROR]: void;
  [EVENTBUS_SOCKET_RECONNECT_FAILED]: void;
};

export const eventBus = mitt<AppEvents>();
